name: Adds all issues that include the 'bug'labels to project board

on:
  issues:
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/ECS-Data-Solutions/projects/5/views/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: bug